//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::episode::Entity as Episode;
pub use super::genre::Entity as Genre;
pub use super::movie::Entity as Movie;
pub use super::season::Entity as Season;
pub use super::subscription::Entity as Subscription;
pub use super::tv::Entity as Tv;
